version: '3.8'

services:
  dvwa_web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - dvwa_db

  dvwa_db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
